image/urls.py
from django.contrib import admin
from django.urls import path
from . import settings
from image_app.views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('image_upload',Alphabet_img_view,name = 'image_upload'),
    path('success',success,name='success')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

image_app/models.py
from django.db import models


# Create your models here.
class Alphabet(models.Model):
	name = models.CharField(max_length = 50)
	Alphabet_img = models.ImageField(upload_to = 'images/')
	#number = models.CharField(max_length=5, blank=True)
	

	
	

image_app/forms.py
from django import forms
from .models import *

class AlphabetForm(forms.ModelForm):
	number = 0
	img = ''
	class Meta:
		model = Alphabet
		fields = ['Alphabet_img']

image_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from .models import *
import keras
from keras.preprocessing import image
from django.core.files.storage import FileSystemStorage


# Create your views here.
def predictor(file):
	model = keras.models.load_model('image_app/my_model.h5')
	img = image.load_img('media/images/'+ file)
	img2  = image.img_to_array(img)
	img3  = img2.reshape((1,) + img2.shape)
	predict = model.predict_classes(img3)[0]
	return str(predict)

def Alphabet_img_view(request):

	if request.method == "POST":
		form = AlphabetForm(request.POST,request.FILES)
		#post = request.POST # if using normal forms
		print("\n\n THE print Statement  ")
		print(request.FILES['Alphabet_img'].name) # to get info  from normal forms
		file = request.FILES['Alphabet_img'].name
		print("\n\n")

		if form.is_valid():
			form.save()
			predict = predictor(file)
			print(predict)
			AlphabetForm.number = predict
			AlphabetForm.img = "media/images/"+request.FILES['Alphabet_img'].name
			#return redirect('success',predict)
			#return HttpResponse("The number is: "+predict)
	else:
		form = AlphabetForm()

	return render(request,'image_app/page.html',{'form':form})

def success(request):	
	return HttpResponse('success')



		

image_app/templates/image_app/page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Alphabet Image</title>
	<link href = "./static/css/style.css" type = "text/css" rel = "stylesheet"> 
</head>

<body>
	<div class = top>
		<h2>MNIST Model</h2>
		<br>
	</div>
	
	<div class= images>
		<h3>Built using:</h3>

		<div class = col>
		<img src = "static/images/django-logo-negative.png" > 
		</div>

	    <div class = col>
		<img src = "static/images/logo-k-keras-wb.png" >
		</div> 

		<div class = col>
		<img src = "static/images/python.png" >
		</div>

		<div class = col>
		<img src = "static/images/css html.png" >
		</div>

	</div>
	  
	<div class= bkground>
	<div class = upload>
		<h4> Upload image here:</h4>
		<form method = "POST" enctype="multipart/form-data">
			{% csrf_token %}		
			<p><label for="id_Alphabet_img"></label> 
				
				<input type="file" name="Alphabet_img" accept="image/*" required id="id_Alphabet_img"></p>

			<button type="submit">Upload</button>	
		</form><br>
	</div>
</div>
<br>

	<div class="ans">
		<h3> <!-- <img src = {{form.img}}> --> The number is: <br><strong>{{form.number}}</strong></h3><img src = {{form.img}}>
	</div>
		
</body>
</html>